meta:
  name: 'StudyForTwo Kokugakuin'
  title: 'StudyForTwo Kokugakuin - オンライン教科書予約'
  description: '國學院大学を拠点に国際協力を行っている学生団体STUDYFORTWOです。講義で使わなくなった教科書を回収、半額で販売し、売り上げで途上国の子どもたちに教育支援を行なっています。オンラインでは、欲しい教科書の予約ができます。'
  keywords: '國學院大学,途上国支援,教科書'
  og:
    type: 'website'


